### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by tempo550** [LlamaPag/bastion#1]
Hi. Please return the 'click the chat' option to end a run. I preferred that option to the drop pickaxe and don't find it redundant. Also I would like the option to generate Nether fortresses. I know you added spawners recently, but the fortresses themselves would be good also.

**Comment by LlamaPag** [comment]
Whats up man, I'm not planning on bringing back the chat reset option as the map is currently built around the drop pick option instead and its arguably a better system.
I actually just got on Github to update the map with a fortress option for piedar so that's convenient.
Appreciate the feedback! :)

**Comment by tempo550** [comment]
No worries thanks for a great map pack. One other minor thing that I think could be improved upon, is when bastions generate sometimes a stray lava source block streams down from top into the tunnels. Usually I reset for these.

**Comment by LlamaPag** [comment]
Yeah I haven't really figured out a good way to go about that issue yet. Searching a volume larger than the bastion for singular lava blocks is expensive and would significantly increase load times.
Maybe I could add a hidden option to toggle lava clearing in a later update.
